import Button from '@mui/material/Button';
import type { NextPage } from 'next';
import Head from 'next/head';
import { FunctionComponent } from 'react';
import { sample } from 'store/sample';
import styles from 'styles/Home.module.css';

const Counter: FunctionComponent = () => {
  const { bears, increasePopulation, removeAllBears } = sample();

  const increase = (e: React.MouseEvent) => {
    increasePopulation(bears);
  };

  const reset = (e: React.MouseEvent) => {
    removeAllBears();
  };

  return (
    <div className="counter">
      <span>{bears}</span>
      <Button onClick={increase} variant="outlined">
        one up
      </Button>
      <Button onClick={reset}>one up</Button>
    </div>
  );
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Counter />
    </div>
  );
};

export default Home;
